#ifndef SPDK_CONFIG_H
#define SPDK_CONFIG_H

#define SPDK_CONFIG_PREFIX /usr/local
#define SPDK_CONFIG_DEBUG 1
#undef SPDK_CONFIG_LOG_BACKTRACE
#define SPDK_CONFIG_WERROR 1
#undef SPDK_CONFIG_LTO
#undef SPDK_CONFIG_COVERAGE
#undef SPDK_CONFIG_ASAN
#undef SPDK_CONFIG_UBSAN
#undef SPDK_CONFIG_TSAN
#define SPDK_CONFIG_TESTS 1
#define SPDK_CONFIG_ENV /home/pwodkowx/Private/spdk/lib/env_dpdk
#define SPDK_CONFIG_DPDK_DIR /home/pwodkowx/Private/spdk/dpdk/build
#undef SPDK_CONFIG_FIO_PLUGIN
#undef SPDK_CONFIG_FIO_SOURCE_DIR
#undef SPDK_CONFIG_RDMA
#undef SPDK_CONFIG_RDMA_SEND_WITH_INVAL
#undef SPDK_CONFIG_RBD
#define SPDK_CONFIG_VHOST 1
#define SPDK_CONFIG_VIRTIO 1
#undef SPDK_CONFIG_PMDK
#undef SPDK_CONFIG_PMDK_DIR
#undef SPDK_CONFIG_VPP
#undef SPDK_CONFIG_ISCSI_INITIATOR
#undef SPDK_CONFIG_CRYPTO
#define SPDK_CONFIG_SHARED 1
#undef SPDK_CONFIG_VTUNE
#undef SPDK_CONFIG_VTUNE_DIR

#endif /* SPDK_CONFIG_H */

