[global]
thread=1

[check_zeroes]
rw=read
do_verify=1
verify=pattern
verify_pattern=0x00
filename=

[write_verify]
rw=write
do_verify=1
verify=md5
verify_backlog=1024
verify=md5
filename=

[fill_70_percent]
rw=write
size=
filename=

[fill_45_percent]
rw=write
size=
filename=

[fill_100_percent]
rw=write
size=
filename=

[fill_100_percent_with_offset]
rw=write
offset=
size=
filename=


[fill_100_percent_verify]
rw=write
do_verify=1
verify=md5
verify_backlog=1024
size=
filename=
