#  SPDX-License-Identifier: BSD-3-Clause
#  Copyright (C) 2016 Intel Corporation.
#  All rights reserved.
#

SPDK_ROOT_DIR := $(abspath $(CURDIR)/../../../../..)

SPDK_LIB_LIST = blob
TEST_FILE = blobfs_sync_ut.c

include $(SPDK_ROOT_DIR)/mk/spdk.unittest.mk
