#!/usr/bin/env bash

SYSTEM=`uname -s`
if [ $SYSTEM = "FreeBSD" ] ; then
    echo "blobstore.sh cannot run on FreeBSD currently."
    exit 0
fi

set -xe

testdir=$(readlink -f $(dirname $0))
rootdir=$(readlink -f $testdir/../..)
source $rootdir/scripts/autotest_common.sh
timing_enter blobstore

set -e

# Nvme0 target configuration
$rootdir/scripts/gen_nvme.sh > $testdir/blobcli.conf
dd if=/dev/urandom of=$testdir/test.pattern bs=1M count=1
$rootdir/examples/blob/cli/blobcli -c $testdir/blobcli.conf -b Nvme0n1 -T $testdir/test.bs > btest.out

# the tool leaves some trailing whitespaces that we need to strip out
sed -i 's/[[:space:]]*$//' ./btest.out

# the test script will import the test pattern generated by dd and then export
# it to a file so we can compare and confirm basic read and write
diff test.pattern test.pattern.blob
$rootdir/test/app/match/match ./btest.out.match

rm -rf $testdir/blobcli.conf
rm -rf ./*.blob
rm -rf ./test.pattern

timing_exit blobstore
