[global]
ioengine=libaio
runtime=30
filename=
group_reporting
thread
numjobs=1
direct=1
do_verify=1
verify=md5
verify_backlog=1024

[read]
stonewall
rw=read
bs=4k
iodepth=16

[write]
stonewall
rw=write
bs=64k
iodepth=32

[rw]
stonewall
rw=rw
bs=128K
iodepth=64

[randread]
stonewall
rw=randread
bs=256k
iodepth=128

[randwrite]
stonewall
rw=randwrite
bs=512k
iodepth=256

[randrw]
stonewall
rw=randrw
bs=1024k
iodepth=512
