#!/usr/bin/env bash
set -xe

rootdir=$(readlink -f $(dirname $0))

# we can add some actions to clean up files which no need anymore, such as share memory overflow...
echo "delete trace pid files which generated by spdk targets except the alive one"
PID=`ps -ef| grep "\(spdk_tgt\|nvmf_tgt\|iscsi_tgt\|vhost\)"| grep -v grep | awk '{print $2}'`
#find the target PID
if [ ! $PID ]
then
	echo "no target is running!,delete trace_pid and conns files"
	rm -rf /dev/shm/*trace.pid*
	rm -rf /dev/shm/spdk_*_conns.*
else
	echo $PID
	# delete files exclues the alive one
	find /dev/shm/* ! -name *trace.pid$PID* | xargs rm -rf
fi
