#!/usr/bin/env bash

set -xe

rootdir=$(readlink -f $(dirname $0))

# we can add some actions to clean up files which no need anymore, such as share memory overflow...
echo "delete trace pid files which generated by spdk targets"
rm -f  /dev/shm/*trace.pid*
echo "delete conns files"
rm -f  /dev/shm/spdk_*_conns.*
