import pexpect

child = pexpect.spawn('python ./spdkcli.py')
child.expect("/>")
child.sendline("ls")
child.expect("/>")
print child.before
child.sendline("/bdevs/Malloc create 32 512 Malloc0")
child.expect("/>")
child.sendline("/bdevs/Malloc create 32 512 Malloc1")
child.expect("/>")
child.sendline("/bdevs/Malloc create 32 512 Malloc2")
child.expect("/>")
child.sendline("/lvol_stores create lvs Malloc0")
child.expect("/>")
child.sendline("/bdevs/Error create Malloc1")
child.expect("/>")
child.sendline("/bdevs/Split_Disk split_bdev Malloc2 2")
child.expect("/>")
child.sendline("/bdevs/Logical_Volume create lvol 16 lvs")
child.expect("/>")
child.sendline("/bdevs/Null create null_bdev 32 512")
child.expect("/>")
child.sendline("ls")
child.expect("/>")
print child.before
child.sendline("/bdevs/Null delete null_bdev")
child.expect("/>")
child.sendline("/bdevs/Logical_Volume delete lvs/lvol")
child.expect("/>")
child.sendline("/bdevs/Split_Disk destruct_split_bdev Malloc2")
child.expect("/>")
child.sendline("/lvol_stores delete lvs")
child.expect("/>")
child.sendline("/bdevs/Malloc delete Malloc0")
child.expect("/>")
child.sendline("/bdevs/Malloc delete Malloc1")
child.expect("/>")
child.sendline("/bdevs/Malloc delete Malloc2")
child.expect("/>")
child.sendline("ls")
child.expect("/>")
print child.before
child.close()
