// Make sure all of the SPDK public headers compile as C++

extern "C" {
#include "spdk/assert.h"
#include "spdk/barrier.h"
#include "spdk/bdev.h"
#include "spdk/bit_array.h"
#include "spdk/conf.h"
#include "spdk/copy_engine.h"
#include "spdk/endian.h"
#include "spdk/event.h"
#include "spdk/fd.h"
#include "spdk/gpt_spec.h"
#include "spdk/ioat.h"
#include "spdk/ioat_spec.h"
#include "spdk/iscsi_spec.h"
#include "spdk/json.h"
#include "spdk/jsonrpc.h"
#include "spdk/likely.h"
#include "spdk/log.h"
#include "spdk/mmio.h"
#include "spdk/net.h"
#include "spdk/nvme.h"
#include "spdk/nvme_intel.h"
#include "spdk/nvme_spec.h"
#include "spdk/nvmf_spec.h"
#include "spdk/pci.h"
#include "spdk/pci_ids.h"
#include "spdk/queue.h"
#include "spdk/rpc.h"
#include "spdk/scsi.h"
#include "spdk/scsi_spec.h"
#include "spdk/string.h"
#include "spdk/trace.h"
#include "spdk/vtophys.h"
}
